import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { NavigationMenuDemo } from "@/components/ui/navigation";
import ToastProvider from "@/components/Toastify";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="bg-gray-500 p-2">
                    <NavigationMenuDemo />
                </div>
                <main className="max-w-7xl m-auto">
                    <ToastProvider>{children}</ToastProvider>
                </main>
            </body>
        </html>
    );
}
